version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: b3
      RABBITMQ_DEFAULT_PASS: b3
      RABBITMQ_ERLANG_COOKIE: "ErlangCookie"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
