version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "ErlangCookie"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ./rb_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_PID: "Express"
      SA_PASSWORD: "todolist123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sqldata:/var/opt/mssql/data
      - ./scripts.sql:/var/opt/mssql/scripts/scripts.sql
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=false
    volumes:
      - ./el_data:/usr/share/elasticsearch/data/
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    hostname: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kb_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
  api:
    image: api 
    build:
      context:  /
      dockerfile: src/TodoList.Api/Dockerfile
    hostname: api
    ports:
      - "9000:80"
    depends_on:
    - kibana
    - rabbitmq
    - sqlserver
    - elasticsearch
  worker:
    image: worker 
    build:
      context:  /
      dockerfile: src/TodoList.Worker/Dockerfile
    hostname: worker
    depends_on:
    - kibana
    - rabbitmq
    - sqlserver
    - elasticsearch
  web:
    image: web
    build:
      context: src/todolist.web
    hostname: web
    ports:
      - "3000:3000"
    depends_on:
      - api