// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.Infrastructure.Data.Pagination;

#nullable disable

namespace TodoList.Api.Migrations
{
    [DbContext(typeof(TodoListContext))]
    [Migration("20240517221338_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoList.Core.Tasks.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID")
                        .HasComment("Campo com os valores de chave primária.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValue(new DateTime(2024, 5, 17, 19, 13, 38, 582, DateTimeKind.Local).AddTicks(8867))
                        .HasColumnName("CRIADO_EM")
                        .HasComment("Campo com os valores da data de criação da tarefa.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("DESCRICAO")
                        .HasComment("Campo com os valores da descrição da tarefa.");

                    b.Property<int>("Status")
                        .HasColumnType("INT")
                        .HasColumnName("STATUS")
                        .HasComment("Campo com os valores do status da tarefa.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("TITULO")
                        .HasComment("Campo com os valores do título da tarefa.");

                    b.HasKey("Id");

                    b.ToTable("TB_TAREFAS", null, t =>
                        {
                            t.HasComment("Tabela de tarefas");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
